In [1]:
import numpy as np
import pandas as pd

In [2]:
data = [
    [1, 'Smith', 50000],
    [2, 'Jones', 60000]
]

df = pd.DataFrame(data)
df

   0      1      2
0  1  Smith  50000
1  2  Jones  60000

In [3]:
df.columns = ['Empd', 'Name', 'Salary']
df

   Empd   Name  Salary
0     1  Smith   50000
1     2  Jones   60000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Empd    2 non-null      int64
 1   Name    2 non-null      str
 2   Salary  2 non-null      int64
dtypes: int64(2), str(1)
memory usage: 190.0 bytes

In [5]:
df = pd.read_csv("employee.csv")
df

   emp id                   name  salary
0       1      SREE VARSSINI K S    5000
1       2            SREEMATHI B    6000
2       3                SREYA G    7000
3       4   SREYASKARI MULLAPUDI    5000
4       5          SRI AKASH U G    8000
5       6  SRI HARSHAVARDHANAN R    3000
6       7  SRI HARSHAVARDHANAN R    6000

In [6]:
df.head()

   emp id                  name  salary
0       1     SREE VARSSINI K S    5000
1       2           SREEMATHI B    6000
2       3               SREYA G    7000
3       4  SREYASKARI MULLAPUDI    5000
4       5         SRI AKASH U G    8000

In [7]:
df.tail()

   emp id                   name  salary
2       3                SREYA G    7000
3       4   SREYASKARI MULLAPUDI    5000
4       5          SRI AKASH U G    8000
5       6  SRI HARSHAVARDHANAN R    3000
6       7  SRI HARSHAVARDHANAN R    6000

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   emp id  7 non-null      int64
 1   name    7 non-null      str
 2   salary  7 non-null      int64
dtypes: int64(2), str(1)
memory usage: 410.0 bytes

In [9]:
df.salary

0    5000
1    6000
2    7000
3    5000
4    8000
5    3000
6    6000
Name: salary, dtype: int64

In [10]:
type(df.salary)

pandas.Series

In [11]:
df.salary.mean()

np.float64(5714.285714285715)

In [12]:
df.salary.median()

np.float64(6000.0)

In [13]:
df.salary.mode()

0    5000
1    6000
Name: salary, dtype: int64

In [14]:
df.salary.var()

np.float64(2571428.5714285714)

In [15]:
df.salary.std()

np.float64(1603.5674514745463)

In [16]:
df.describe()

         emp id       salary
count  7.000000     7.000000
mean   4.000000  5714.285714
std    2.160247  1603.567451
min    1.000000  3000.000000
25%    2.500000  5000.000000
50%    4.000000  6000.000000
75%    5.500000  6500.000000
max    7.000000  8000.000000

In [17]:
df.describe(include='all')

          emp id                   name       salary
count   7.000000                      7     7.000000
unique       NaN                      6          NaN
top          NaN  SRI HARSHAVARDHANAN R          NaN
freq         NaN                      2          NaN
mean    4.000000                    NaN  5714.285714
std     2.160247                    NaN  1603.567451
min     1.000000                    NaN  3000.000000
25%     2.500000                    NaN  5000.000000
50%     4.000000                    NaN  6000.000000
75%     5.500000                    NaN  6500.000000
max     7.000000                    NaN  8000.000000

In [18]:
empCol = df.columns
empCol

Index(['emp id', 'name', 'salary'], dtype='str')

In [19]:
emparray = df.values
emparray

array([[1, 'SREE VARSSINI K S', 5000],
       [2, 'SREEMATHI B', 6000],
       [3, 'SREYA G', 7000],
       [4, 'SREYASKARI MULLAPUDI', 5000],
       [5, 'SRI AKASH U G', 8000],
       [6, 'SRI HARSHAVARDHANAN R', 3000],
       [7, 'SRI HARSHAVARDHANAN R', 6000]], dtype=object)

In [20]:
employee_DF = pd.DataFrame(emparray, columns=empCol)
employee_DF

  emp id                   name salary
0      1      SREE VARSSINI K S   5000
1      2            SREEMATHI B   6000
2      3                SREYA G   7000
3      4   SREYASKARI MULLAPUDI   5000
4      5          SRI AKASH U G   8000
5      6  SRI HARSHAVARDHANAN R   3000
6      7  SRI HARSHAVARDHANAN R   6000